### ISSUE TITLE
Sizes of  tensors not match

### ISSUE THREAD

**Issue by ShowTsai** [ternaus/robot-surgery-segmentation#18]
I use my own dataset to train in binary mode
There are 54600 jpg images and 54600 jpg masks
They are all in shape (540, 540, 3)
I change the code in prepare_data.py because my images are jpg, not png
```python3
cv2.imwrite(str(binary_mask_folder / file_name.name).replace('jpg', 'png'), mask_binary)
```

I ran train.py by the script:
``
python train.py --device-ids 0 --batch-size 1 --lr 0.0001 --n-epochs 10 --type binary --jaccard-weight --model UNet
``

I got the error:
```linux
Traceback (most recent call last):
  File "train.py", line 139, in <module>
    main()
  File "train.py", line 134, in main
    num_classes=num_classes
  File "/home/rpss0322/rpss/cellphone_defect_segmentation/utils.py", line 66, in train
    outputs = model(inputs)
  File "/home/rpss0322/rpss/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rpss0322/rpss/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py", line 121, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/rpss0322/rpss/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rpss0322/rpss/cellphone_defect_segmentation/models.py", line 382, in forward
    x_out = up(torch.cat([x_out, x_skip], 1))
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 67 and 64 in dimension 2 at /pytorch/aten/src/THC/generic/THCTensorMath.cu:87
```

I changed the model to UNet11, and I got the error:
```linux
Traceback (most recent call last):
  File "train.py", line 139, in <module>
    main()
  File "train.py", line 134, in main
    num_classes=num_classes
  File "/home/rpss0322/rpss/cellphone_defect_segmentation/utils.py", line 66, in train
    outputs = model(inputs)
  File "/home/rpss0322/rpss/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rpss0322/rpss/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py", line 121, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/rpss0322/rpss/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rpss0322/rpss/cellphone_defect_segmentation/models.py", line 112, in forward
    dec5 = self.dec5(torch.cat([center, conv5], 1))
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 33 and 32 in dimension 2 at /pytorch/aten/src/THC/generic/THCTensorMath.cu:87
```

Are the issues caused by the type of images?
or there are other reasons?
Thanks!

**Comment by ternaus** [comment]
Input image sizes for UNet type architectures with `N` max-pooling layers should be divisible by `2^N`.

In this repo, I am using networks with `N=5`. 

I added checks for this in https://github.com/ternaus/robot-surgery-segmentation/commit/eaa75ab2e3e3e32b655b3eeb5a7d614d55e5f260

The easiest way for you may be to use 

`RandomCrop` for the train. `CenterCrop` for validation and combination of `PadIfNeeded` + `Crop` for inference.

`RandomCrop`, `Crop`, `CenterCrop` and `PadIfNeeded` are defined in https://albumentations.readthedocs.io/en/latest/api/augmentations.html
